### ISSUE TITLE
Basic Structure for Scenes

### ISSUE THREAD

**Issue by VanSubstance** [VanSubstance/To-the-North#1]
필요한 씬들의 기본 구성
문서 작업 선행

**Comment by VanSubstance** [comment]
실제 유니티 프로젝트 생성 후 Scene 생성

**Comment by VanSubstance** [comment]
Scene 기본 선언 완료
-> Scene 사이의 기본적인 이동 기능
| 1. RS, FR, NFR 작성
| 2. 실 구현

**Comment by VanSubstance** [comment]
FlowChart, RS, Class Diagram 작성 완료
실 구현 시작

**Comment by VanSubstance** [comment]
>  xptmxm
가나다 가나다
> ㅁㅇㅁㄴ
ㅁㄴㅇㅁ
ㄴㅇ

**Comment by VanSubstance** [comment]
추가 구조의 필요성::
> 공지 메세지 = 시스템 메세지 출력을 위한 구조
문서 작업 선행

**Comment by VanSubstance** [comment]
공지 메세지, 기초 애니메이션 관련 작업 완료
다음 과업 완료 후 이슈 닫기
> 씬 간 이동 기능

**Comment by kang123077** [comment]
Test Comment
