### ISSUE TITLE
Map: Shelter

### ISSUE THREAD

**Issue by VanSubstance** [VanSubstance/To-the-North#101]
기본적인 거주지 구성
아래의 설정에 따라서 구성해볼 것

+ 기존의 다른 Scene들 삭제
추후 기획 + 디자인된 구획들부터 순차적으로 구현할 것

https://projectto-the-north.slack.com/archives/C04R69Z41HB/p1680539160850479

**Comment by kang123077** [comment]
> 구매한 에셋 프리팹 화 작업 중
- [x] 바닥 종류
- [x] 벽 종류

**Comment by kang123077** [comment]
#### 해당 이슈는 선행 이슈 해결 후 다시 작성 할 예정입니다
