### ISSUE TITLE
Inventory: Item Interaction Event

### ISSUE THREAD

**Issue by kang123077** [VanSubstance/To-the-North#128]
- [x] 아이템 자동 정렬 알고리즘 (위치를 가지지 않는 아이템 전달 or 즉시 이동 시)
- [x] 루팅, 바닥, Equipment(해당 장비 칸으로?) 의 경우 Ctrl + 왼 클릭시 즉시 이동
- [x] 탄환 -> 탄창 위로 끌어서 삽탄 + 드래그 앤 드롭 시 발생하는 버그 수정
- [x] 탄창, 탄환 등 현재 잔탄수나 잔여량이 보여야 하는 (= 수량이 있는) 경우, 숫자 가시화
- [x] 탄창 장착 해제 시 자동으로 인벤토리로 이동
- [x] 탄창 장착 시 자동으로 인벤토리에서 삭제

_Originally posted by @kang123077 in https://github.com/VanSubstance/To-the-North/issues/97#issuecomment-1498674047_

**Comment by VanSubstance** [comment]
2D -> 3D 코어 이식

**Comment by VanSubstance** [comment]
:: 리팩토링 완료 ::
이제 체크리스트 과업 시작
