### ISSUE TITLE
Varietion of Modal Contents

### ISSUE THREAD

**Issue by VanSubstance** [VanSubstance/To-the-North#17]
기본 모달 시스템 구상 완료
모달의 종류에 따라, 내부 컨텐츠가 모듈 형태로 추가되어야 함
1. ...

종류는 진행하면서 추가 요망

**Comment by VanSubstance** [comment]
기본 틀(예시) 컨텐츠 컨트롤러 두개 존재
1. 그냥 텍스트 보여주기
2. 그냥 값 받기

재단 필요
1. 그냥 텍스트 보여주기 -> 제목, 내용으로 택스트 나눠받아 보여주기
2. 그냥 값 받기 -> 제목, 입력값 칸으로 나눠서 제목은 받아서 보여주기

**Comment by VanSubstance** [comment]
conditionConfirm 함수 응용해서 에러 분기 나눠서 처리하기

**Comment by VanSubstance** [comment]
작업 순서
1. 기존 FlowChart 기존 코드 기반 업데이트
2. 기존 RS 업데이트된 FlowChart 기반 업데이트
3. 새로운 로직 기반으로 FlowChart 업데이트
4. 업데이트된 FC 기반으로 RS 업데이트
5. 실 개발 -> Class Diagram

**Comment by VanSubstance** [comment]
종류 추가 필요:
- int x, y 두개의 값을 받는 모달

**Comment by kang123077** [comment]
현재로선 MapEditor한정의 FlowChart-Popup-Modal
(Title추가가 아닌 Variation 고려 시 구조에 대한 질문 필요)

**Comment by kang123077** [comment]
modalTitle은 추가되었지만 레이아웃, 바리에이션 등에 대해서 논의 필요

**Comment by VanSubstance** [comment]
해당 이슈 전면 중지
> 우선도가 맨 밑으로 내려감
