### ISSUE TITLE
Event: Rooting

### ISSUE THREAD

**Issue by VanSubstance** [VanSubstance/To-the-North#53]
루팅 이벤트 고안
> 아이템 프리펩이 기본적으로 고안이 완료되었음
> 스페이스바를 눌렀을 때, 루팅 창이 열려야 함

**Comment by VanSubstance** [comment]
기본적인 루팅 프리펩 구성 필요
@VanSubstance

**Comment by VanSubstance** [comment]
루팅 프리펩 구성 완료
- 기능 구현이 필요 @kang123077

**Comment by VanSubstance** [comment]
참고할 스크립트::
- EventPortalController

실제 작업이 필요한 스크립트::
- EventRootingController

**Comment by kang123077** [comment]
이전 Issue에서 누락된 아이템 마우스 이벤트 우선 처리 예정
- [ ] itemSize만큼 isAttached 활성화
- [ ] isAttached의 서순 수정

**Comment by kang123077** [comment]
아이템 이슈 정리
아이템 컨테이너에는 자동정렬 기능이 존재한다
아이템 컨테이너 인스턴스화에는 두 종류가 있다
> 생성 동시에 자동 정렬 되는 것
> 생성 동시에 자동 정렬 되지 않는 것 (위치정보를 기억)
> 후자의 경우 아이템이 위치정보를 가지고 있을 가능성
비정형 아이템은 존재하지 않는다
아이템은 들고 있는 상태에서 R을 눌러서 회전시킬 수 있다
아이템의 회전은 이미지, 구조가 90도 회전된다
R을 다시 누르면 원래대로 돌아온다

**Comment by kang123077** [comment]
아이템 마우스 이벤트 기능 추가를 위한 리팩토링 필요
- [ ] 아이템이 슬롯 위에 올라왔을 때, 설치가 가능하면 아이템 슬롯의 색상 변경

**Comment by kang123077** [comment]
- [ ] 드래그 도중 R키를 클릭 시 아이템 회전 기능 추가
