### ISSUE TITLE
Inventory: Container for Item

### ISSUE THREAD

**Issue by VanSubstance** [VanSubstance/To-the-North#97]
Container = 아이템들을 보관하는 슬롯 칸들 모음을 의미
- Container Prefab에는 두가지 종류가 있다.
> ContainerPure Prefab
> ContainerEuipment Prefab

ItemForUI = 컨테이너에서 사용할 아이템 프리펩을 의미

Inventory = 기본적으로 내 아이템들 관련 상호작용을 하는 UI를 의미
- Inventory UI Prefab의 구성요소는 기본적으로 아래를 포함한다:
> 창 (14, 7 사이즈?)
> 좌/ 우에 Container를 올릴 수 있음
> 좌 상단에 북마크 있음
> - 북마크의 종류는 1. Root + Equipment, 2. Store + Equipment 둘 중 하나 조합이 온다.
> 우 상단에 소지금 있음
> - 판매 or 구매 시 예상 변동 금액이 위에 뜰 수 있음

**Comment by kang123077** [comment]
- [ ] 아이템 자동 정렬 알고리즘 (위치를 가지지 않는 아이템 전달 or 즉시 이동 시)
- [ ] 루팅, 바닥, Equipment(해당 장비 칸으로?) 의 경우 Ctrl + 왼클릭시 즉시 이동

**Comment by kang123077** [comment]
EquipContainer의 경우 MiddleSection에서 다루는 방향으로 변경

- [ ] 아이템 중앙 지점 관련 고려
- [ ] EquipSlot의 경우 장착 위치 고려

**Comment by VanSubstance** [comment]
인벤토리 시스템 ~ 장착 시스템 간의 1차 Integration 완료

:: 현재 확인된 문제점 ::
- 최초 위치가 제대로 안잡힘
- 사이즈에 따른 scaling이 이루어지지 않음
- 그 외의 자잘한 문제 있을 것으로 예상

코드 차분히 보신 뒤 질문이 있으시다면 바로바로 해주시면 됩니당 :))

**Comment by kang123077** [comment]
- [x] OverlapPoint로 리팩토링
